set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)

set(CHEERP 1)

SET(CMAKE_C_FLAGS_INIT "-target cheerp")
SET(CMAKE_CXX_FLAGS_INIT "-target cheerp")

set(CMAKE_STATIC_LIBRARY_SUFFIX ".bc")
set(CMAKE_EXECUTABLE_SUFFIX ".js")
set(CMAKE_CXX_CREATE_STATIC_LIBRARY "/opt/cheerp/bin/llvm-link <OBJECTS> -o <TARGET>")
set(CMAKE_C_CREATE_STATIC_LIBRARY "/opt/cheerp/bin/llvm-link <OBJECTS> -o <TARGET>")

SET(CMAKE_SYSTEM_INCLUDE_PATH "/include")
